using System.Security.Cryptography;
using CoupleSync.Infrastructure.Integrations.Pluggy;
using CoupleSync.Infrastructure.Security;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace CoupleSync.UnitTests.OpenFinance;

/// <summary>Issue #24 — AES-256-GCM of the Open Finance credentials. Every key here is generated by the test.</summary>
[Trait("Category", "OpenFinance")]
public sealed class AesGcmCredentialCipherTests
{
    private const string Secret = "fake-client-secret-not-real-9f8e7d6c";

    private static string NewKey() => Convert.ToBase64String(RandomNumberGenerator.GetBytes(32));

    private static AesGcmCredentialCipher Cipher(string? key)
        => new(Options.Create(new OpenFinanceOptions { EncryptionKey = key ?? string.Empty }), NullLogger<AesGcmCredentialCipher>.Instance);

    [Fact]
    public void Encrypt_ThenDecrypt_GivesTheValueBack_AndTheStoredTextIsNotTheValue()
    {
        var cipher = Cipher(NewKey());

        var stored = cipher.Encrypt(Secret);

        Assert.True(cipher.IsAvailable);
        Assert.NotEqual(Secret, stored);
        Assert.DoesNotContain(Secret, stored, StringComparison.Ordinal);
        Assert.DoesNotContain(Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(Secret)), stored, StringComparison.Ordinal);
        Assert.True(cipher.TryDecrypt(stored, out var back));
        Assert.Equal(Secret, back);
    }

    [Fact]
    public void Encrypt_UsesANewNoncePerValue_TheSameValueNeverGivesTheSameText()
    {
        var cipher = Cipher(NewKey());

        var texts = Enumerable.Range(0, 50).Select(_ => cipher.Encrypt(Secret)).ToList();

        Assert.Equal(50, texts.Distinct(StringComparer.Ordinal).Count());
        // The nonce (bytes 1..12 of the stored value) is different each time too.
        Assert.Equal(50, texts.Select(t => Convert.ToHexString(Convert.FromBase64String(t).AsSpan(1, 12))).Distinct().Count());
    }

    [Theory]
    [InlineData("")]
    [InlineData("ç ã é — 日本語 🔑")]
    public void Encrypt_RoundTripsEmptyAndNonAsciiValues(string value)
    {
        var cipher = Cipher(NewKey());

        Assert.True(cipher.TryDecrypt(cipher.Encrypt(value), out var back));
        Assert.Equal(value, back);
    }

    [Fact]
    public void TryDecrypt_WithAnotherKey_IsFalse()
    {
        var stored = Cipher(NewKey()).Encrypt(Secret);

        Assert.False(Cipher(NewKey()).TryDecrypt(stored, out var back));
        Assert.Equal(string.Empty, back);
    }

    [Fact]
    public void TryDecrypt_OfATextThatWasChanged_IsFalse_WhicheverByteChanged()
    {
        var cipher = Cipher(NewKey());
        var bytes = Convert.FromBase64String(cipher.Encrypt(Secret));

        for (var i = 0; i < bytes.Length; i++)
        {
            var tampered = (byte[])bytes.Clone();
            tampered[i] ^= 0x01;
            Assert.False(cipher.TryDecrypt(Convert.ToBase64String(tampered), out _), $"byte {i} changed and the text was still accepted");
        }
    }

    [Theory]
    [InlineData("")]
    [InlineData("not base64 !!")]
    [InlineData("AQID")] // 3 bytes: shorter than version + nonce + tag
    public void TryDecrypt_OfSomethingThatIsNotAStoredValue_IsFalse(string text)
    {
        Assert.False(Cipher(NewKey()).TryDecrypt(text, out _));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("not-base64-at-all!!")]
    [InlineData("c2hvcnQta2V5")]                                        // 9 bytes
    [InlineData("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")] // 49 bytes
    public void WithoutAKeyOf32BytesInBase64_TheCipherIsUnavailable_AndNeverInventsAKey(string? key)
    {
        var cipher = Cipher(key);

        Assert.False(cipher.IsAvailable);
        Assert.Throws<InvalidOperationException>(() => cipher.Encrypt(Secret));
        Assert.False(cipher.TryDecrypt(Cipher(NewKey()).Encrypt(Secret), out _));
    }

    [Fact]
    public void TheKeyMayComeWithSpacesAround()
    {
        var key = NewKey();

        var stored = Cipher($"  {key}\n").Encrypt(Secret);

        Assert.True(Cipher(key).TryDecrypt(stored, out var back));
        Assert.Equal(Secret, back);
    }
}
