// <auto-generated />
using System;
using CoupleSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoupleSync.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoupleSync.Domain.Entities.AiConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CoupleId", "UserId", "Version")
                        .IsUnique();

                    b.ToTable("ai_consents", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.AiUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("DayBrt")
                        .HasColumnType("date")
                        .HasColumnName("day_brt");

                    b.Property<DateOnly>("DayUtc")
                        .HasColumnType("date")
                        .HasColumnName("day_utc");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("feature");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("RetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retry_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId", "DayBrt");

                    b.HasIndex("DayUtc", "Provider", "Model");

                    b.ToTable("ai_usage", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.AiUserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime?>("OnboardingAnsweredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarding_answered_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WeeklyEmailEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("weekly_email_enabled");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CoupleId", "UserId")
                        .IsUnique();

                    b.ToTable("ai_user_preferences", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AvailableCreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("available_credit_limit");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("BalanceAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("balance_at_utc");

                    b.Property<DateOnly?>("BalanceCloseDate")
                        .HasColumnType("date")
                        .HasColumnName("balance_close_date");

                    b.Property<DateOnly?>("BalanceDueDate")
                        .HasColumnType("date")
                        .HasColumnName("balance_due_date");

                    b.Property<string>("Brand")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("brand");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("MarketingName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("marketing_name");

                    b.Property<decimal?>("MinimumPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_payment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("NumberMasked")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("number_masked");

                    b.Property<string>("PluggyAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pluggy_account_id");

                    b.Property<string>("Subtype")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subtype");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sync_enabled");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PluggyAccountId")
                        .IsUnique();

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BankConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientIdEncrypted")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("client_id_encrypted");

                    b.Property<string>("ClientIdHint")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("client_id_hint");

                    b.Property<string>("ClientSecretEncrypted")
                        .IsConcurrencyToken()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("client_secret_encrypted");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("HistoryMonths")
                        .HasColumnType("integer")
                        .HasColumnName("history_months");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("label");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("LastSyncAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CoupleId", "UserId")
                        .IsUnique();

                    b.ToTable("bank_connections", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BankItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("ConnectorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("connector_name");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExecutionStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("execution_status");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("PluggyItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pluggy_item_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("CoupleId");

                    b.HasIndex("PluggyItemId")
                        .IsUnique();

                    b.ToTable("bank_items", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("AutoReason")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("auto_reason");

                    b.Property<decimal?>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("BillId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bill_id");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionRaw")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description_raw");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("installment_number");

                    b.Property<int?>("InstallmentTotal")
                        .HasColumnType("integer")
                        .HasColumnName("installment_total");

                    b.Property<Guid?>("LinkedIncomeSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_income_source_id");

                    b.Property<Guid?>("LinkedTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_transaction_id");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<Guid?>("MatchedTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_transaction_id");

                    b.Property<string>("MerchantCategory")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("merchant_category");

                    b.Property<string>("MerchantCnpj")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("merchant_cnpj");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("merchant_name");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PluggyCategory")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("pluggy_category");

                    b.Property<string>("PluggyCategoryId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pluggy_category_id");

                    b.Property<string>("PluggyTransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pluggy_transaction_id");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("ReviewState")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("review_state");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("suggested_category");

                    b.Property<Guid?>("SyncRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_run_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("LinkedIncomeSourceId");

                    b.HasIndex("LinkedTransactionId");

                    b.HasIndex("PluggyTransactionId")
                        .IsUnique();

                    b.HasIndex("SyncRunId");

                    b.HasIndex("UserId");

                    b.HasIndex("CoupleId", "LocalDate");

                    b.HasIndex("CoupleId", "ReviewState");

                    b.ToTable("bank_transactions", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BudgetAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<Guid>("BudgetPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_plan_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPlanId", "Category");

                    b.ToTable("budget_allocations", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BudgetPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("GrossIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_income");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("month");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId", "Month")
                        .IsUnique();

                    b.ToTable("budget_plans", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.CategoryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("keyword");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("Keyword")
                        .IsUnique();

                    b.ToTable("category_rules", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.Couple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("join_code");

                    b.Property<DateTime>("JoinCodeExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("join_code_expires_at_utc");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("couples", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.CoupleMember", b =>
                {
                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("CoupleId", "UserId");

                    b.HasIndex("CoupleId")
                        .IsUnique()
                        .HasDatabaseName("IX_couple_members_one_owner_per_couple")
                        .HasFilter("role = 'Owner'");

                    b.HasIndex("UserId");

                    b.ToTable("couple_members", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "Platform")
                        .IsUnique();

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.EmailCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("IssueCount")
                        .HasColumnType("integer")
                        .HasColumnName("issue_count");

                    b.Property<DateTime>("IssueWindowStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_window_started_at_utc");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose")
                        .IsUnique();

                    b.ToTable("email_codes", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("current_amount");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CoupleId", "Status");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AiCategorizationConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_categorization_consent");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("file_mime_type");

                    b.Property<string>("LineStatesJson")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("line_states_json");

                    b.Property<string>("OcrResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ocr_result_json");

                    b.Property<DateTime?>("QuotaResetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quota_reset_date");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_file_name");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("UserId");

                    b.HasIndex("CoupleId", "Status");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId", "Month");

                    b.HasIndex("UserId", "Month");

                    b.HasIndex("CoupleId", "UserId", "Month", "Name")
                        .IsUnique();

                    b.ToTable("income_sources", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.NotificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alert_type");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("body");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CoupleId", "Status");

                    b.ToTable("notification_events", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BillReminderEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("bill_reminder_enabled");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<bool>("LargeTransactionEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("large_transaction_enabled");

                    b.Property<bool>("LowBalanceEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("low_balance_enabled");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("UserId", "CoupleId")
                        .IsUnique();

                    b.ToTable("notification_settings", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.RecurringStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnnualCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("annual_cost");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cadence");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("confidence");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("EndMonth")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("end_month");

                    b.Property<DateOnly>("FirstSeenLocal")
                        .HasColumnType("date")
                        .HasColumnName("first_seen_local");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("flags");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("installment_number");

                    b.Property<int?>("InstallmentTotal")
                        .HasColumnType("integer")
                        .HasColumnName("installment_total");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<decimal>("LastAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("last_amount");

                    b.Property<DateOnly>("LastSeenLocal")
                        .HasColumnType("date")
                        .HasColumnName("last_seen_local");

                    b.Property<decimal>("MedianAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("median_amount");

                    b.Property<string>("MerchantKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("merchant_key");

                    b.Property<int>("MissedCount")
                        .HasColumnType("integer")
                        .HasColumnName("missed_count");

                    b.Property<string>("NameSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name_source");

                    b.Property<DateOnly?>("NextExpectedLocal")
                        .HasColumnType("date")
                        .HasColumnName("next_expected_local");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences");

                    b.Property<DateTime?>("OverrideAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("override_at_utc");

                    b.Property<Guid?>("OverrideByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("override_by_user_id");

                    b.Property<decimal?>("PreviousAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("previous_amount");

                    b.Property<decimal?>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remaining_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserOverride")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("user_override");

                    b.Property<bool>("VariableAmount")
                        .HasColumnType("boolean")
                        .HasColumnName("variable_amount");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId", "Status");

                    b.HasIndex("CoupleId", "MerchantKey", "Kind", "Cadence")
                        .IsUnique();

                    b.ToTable("recurring_streams", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.RecurringStreamItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid")
                        .HasColumnName("stream_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("StreamId", "TransactionId")
                        .IsUnique();

                    b.ToTable("recurring_stream_items", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AiCategorizationConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_categorization_consent");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<bool>("ForceItemUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("force_item_update");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("TransactionsNew")
                        .HasColumnType("integer")
                        .HasColumnName("transactions_new");

                    b.Property<int>("TransactionsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("transactions_updated");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("Status");

                    b.HasIndex("ConnectionId", "CreatedAtUtc");

                    b.HasIndex(new[] { "ConnectionId" }, "IX_sync_runs_one_open_per_connection")
                        .IsUnique()
                        .HasFilter("status IN ('Pending', 'Running')");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bank");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EventTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp_utc");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<Guid>("IngestEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingest_event_id");

                    b.Property<string>("Merchant")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("merchant");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("GoalId");

                    b.HasIndex("IngestEventId");

                    b.HasIndex("UserId");

                    b.HasIndex("CoupleId", "Category");

                    b.HasIndex("CoupleId", "EventTimestampUtc");

                    b.HasIndex("CoupleId", "Fingerprint")
                        .IsUnique();

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.TransactionEventIngest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bank");

                    b.Property<Guid>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp_utc");

                    b.Property<string>("Merchant")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("merchant");

                    b.Property<string>("RawNotificationTextRedacted")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("raw_notification_text_redacted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("UserId");

                    b.HasIndex("CoupleId", "CreatedAtUtc");

                    b.HasIndex("CoupleId", "EventTimestamp");

                    b.ToTable("transaction_event_ingests", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveCoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTime?>("ActiveCoupleJoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("couple_joined_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCoupleId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.AiConsent", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.AiUserPreference", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.BankItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BankConnection", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BankItem", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.BankConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BankTransaction", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.IncomeSource", null)
                        .WithMany()
                        .HasForeignKey("LinkedIncomeSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoupleSync.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("LinkedTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoupleSync.Domain.Entities.SyncRun", null)
                        .WithMany()
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BudgetAllocation", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.BudgetPlan", "BudgetPlan")
                        .WithMany("Allocations")
                        .HasForeignKey("BudgetPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetPlan");
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BudgetPlan", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", "Couple")
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Couple");
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.CoupleMember", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany("Members")
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.EmailCode", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.Goal", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.ImportJob", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.IncomeSource", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", "Couple")
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Couple");
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.NotificationEvent", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.NotificationSettings", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.RecurringStream", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.RecurringStreamItem", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.RecurringStream", null)
                        .WithMany("Items")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.SyncRun", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.BankConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoupleSync.Domain.Entities.TransactionEventIngest", null)
                        .WithMany()
                        .HasForeignKey("IngestEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.TransactionEventIngest", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoupleSync.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.User", b =>
                {
                    b.HasOne("CoupleSync.Domain.Entities.Couple", null)
                        .WithMany()
                        .HasForeignKey("ActiveCoupleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.BudgetPlan", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.Couple", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CoupleSync.Domain.Entities.RecurringStream", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
